version: '3.8'

name: generall-ai-stack

services:
  telegram-bot-api: # to allow download and upload big files to bot
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      TELEGRAM_LOCAL: "true"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8081:8081"
    restart: always

  bot:
    build: ./app
    volumes:
      - ./data:/app/data:rw,z,bind
      - /var/run/docker.sock:/var/run/docker.sock
      - telegram-bot-api-data:/var/lib/telegram-bot-api # if telegram-bot-api used
    environment:
      - PYTHONUNBUFFERED=1
      - WORKSPACE_ROOT=/opt/generall.ai/Generall.AI
      - TELEGRAM_USE_LOCAL_API=${TELEGRAM_USE_LOCAL_API:-false}
      - TELEGRAM_LOCAL_API_URL=${TELEGRAM_LOCAL_API_URL:-http://localhost:8081}
      - STREAMING_ENABLED=${STREAMING_ENABLED:-false}
    restart: always
    privileged: true
    network_mode: host
    depends_on:
      - telegram-bot-api # if telegram-bot-api used
    env_file:
      - .env

volumes:
  telegram-bot-api-data:
